---

- name: Ensure the PGP key is installed
  apt_key: id=AC40B2F7 state=present url="http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7"

- name: Install HTTPS support for APT
  apt: pkg={{ item }}
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add the passenger deb repo
  copy: src=passenger.list
        dest=/etc/apt/sources.list.d/passenger.list
        owner=root
        mode=0600

- name: Update apt cache
  apt: update_cache=yes

- name: Install ruby, passenger and nginx
  apt: pkg={{ item }}
  with_items:
    - nginx-full
    - passenger
  notify: Restart Nginx

- name: Write passenger.conf
  template: src=passenger-conf.j2
            dest=/etc/nginx/conf.d/passenger.conf
  notify: Restart Nginx



- name: Write nginx.conf
  template: src=nginx-conf.j2
            dest=/etc/nginx/nginx.conf
  notify: Restart Nginx

- name: Delete default vhost
  file: path=/etc/nginx/sites-enabled/default
        state=absent
  notify: Restart Nginx



- name: Write app.conf
  template: src=app-conf.j2 
            dest=/etc/nginx/sites-available/app.conf

- name: Enable app
  file: src=/etc/nginx/sites-available/app.conf
        dest=/etc/nginx/sites-enabled/app.conf
        state=link
  notify:
    - Restart Nginx
